export class TheRouterConstants {
  static readonly ACTION_PREFIX = '__action__';
  static readonly SERVICE_PROVIDE_PREFIX = '__service_provider__';
  static readonly MODULE_INFO_SEPARATOR = '/';
  static readonly ROUTER_MAP_FILE_NAME = 'routeMap.json';

  static readonly THEROUTER_ANNOTATION_NAME = 'name';
  static readonly THEROUTER_PAGE_CLASSPATH = 'routePageClassPath';
  static readonly THEROUTER_PAGE_LAUNCHMODE = 'launchMode';
  static readonly THEROUTER_PAGE_PARAMS = 'params';
  static readonly THEROUTER_ACTION = 'action';
  static readonly THEROUTER_ACTION_PRIORITY = 'priority';
  static readonly THEROUTER_SERVICE_NAME = 'serviceName';
  static readonly THEROUTER_SERVICE_FUNCTION = 'functionName';
  static readonly THEROUTER_SERVICE_SINGLETON = 'singleton';
}