export class DynamicRouteMapDemo {
  public static json = "{\n" +
    "  \"routerMap\": [\n" +
    "    {\n" +
    "      \"name\": \"https://kymjs.com/dynamic/test_demo\",\n" +
    "      \"pageSourceFile\": \"src/main/ets/generated/TheRouterListPage-764262352.ets\",\n" +
    "      \"buildFunction\": \"ListPageBuilder\",\n" +
    "      \"customData\": {\n" +
    "        \"path\": \"https://kymjs.com/dynamic/test_demo\",\n" +
    "        \"launchMode\": \"MOVE_TO_TOP_SINGLETON\",\n" +
    "        \"name\": \"ListPage\"\n" +
    "      },\n" +
    "      \"moduleNodeDir\": \"/Users/kymjs/code/harmony/TheRouter/entry\",\n" +
    "      \"ohmurl\": \"@normalized:N&&&entry/src/main/ets/generated/TheRouterListPage-764262352&\",\n" +
    "      \"bundleName\": \"cn.therouter.app\",\n" +
    "      \"moduleName\": \"entry\"\n" +
    "    }" +
    "  ]\n" +
    "}"
}