export class BaseConstant {
  public static readonly PAGE_A1: string = 'https://kymjs.com/PAGEA1';
  public static readonly PAGE_A2: string = 'https://kymjs.com/PAGEA2';
  public static readonly PAGE_A3: string = 'https://kymjs.com/PAGEA3';
  public static readonly PAGE_A4: string = 'https://kymjs.com/PAGEA4';
  public static readonly PAGE_B1: string = 'https://kymjs.com/PAGEB1';
  public static readonly PAGE_B2: string = 'https://kymjs.com/PAGEB2';
  public static readonly PAGE_B3: string = 'https://kymjs.com/PAGEB3';
  public static readonly PAGE_B4: string = 'https://kymjs.com/PAGEB4';
  public static readonly PAGE_C: string = 'https://kymjs.com/PAGEC';
  public static readonly PAGE_D: string = 'https://kymjs.com/PAGED';
  public static readonly PAGE_BASE1: string = 'https://kymjs.com/Base/PAGE_BASE1';
  public static readonly MAIN_PAGE = 'https://kymjs.com/MainPage';
  public static readonly LIST_PAGE = 'https://kymjs.com/ListPage';
  public static readonly LIST_PAGE1 = 'https://kymjs.com/HelloWorld';
  public static readonly LIST_PAGE2 = 'https://kymjs.com/Hello.+';
  public static readonly ANIM_PAGE1 = 'https://kymjs.com/bind_content_cover_demo1';
  public static readonly ANIM_PAGE2 = 'https://kymjs.com/bind_content_cover_demo2';
  public static readonly ANIM_PAGE3 = 'https://kymjs.com/bind_content_cover_demo3';
  public static readonly CLASS_SERVICE = "https://kymjs.com/service_provider/classtest1";
  public static readonly CLASS_SERVICE2 = "https://kymjs.com/service_provider/classtest2";
  public static readonly TEST_FUN_WITH_RETURN = "https://kymjs.com/action/classaction1";
  public static readonly TEST_FUN_WITH_PARAMS = "https://kymjs.com/action/classaction2";
}